const { runtime } = browser

let options = {
    appToggle: true,
    opacity: 0.5,
    currentTab: 0,
}

const applyStyles = (name, ele, themeColor) => {

}

const highlight = {
    /* Sectioning Root */
    "body": ele => applyStyles("body", ele, "#ff5826"),
    /* Content Sectioning */
    "address": ele => applyStyles("address", ele, "#ff8666"),
    "article": ele => applyStyles("article", ele, "#ffbaa6"),
    "aside": ele => applyStyles("aside", ele, "#ffefe6"),
    "footer": ele => applyStyles("footer", ele, "#fffbeb"),
    "header": ele => applyStyles("header", ele, "#ffffff"),
    "h1": ele => applyStyles("h1", ele, "#ebffeb"),
    "h2": ele => applyStyles("h2", ele, "#c4ffc4"),
    "h3": ele => applyStyles("h3", ele, "#9dff9d"),
    "h4": ele => applyStyles("h4", ele, "#76ff76"),
    "h5": ele => applyStyles("h5", ele, "#4fff4f"),
    "h6": ele => applyStyles("h6", ele, "#29ff29"),
    "hgroup": ele => applyStyles("hgroup", ele, "#00ff00"),
    "main": ele => applyStyles("main", ele, "#23ff00"),
    "nav": ele => applyStyles("nav", ele, "#46ff00"),
    "section": ele => applyStyles("section", ele, "#69ff00"),
    "search": ele => applyStyles("search", ele, "#8cff00"),
    /* Text Content */
    "blockquote": ele => applyStyles("blockquote", ele, "#afff00"),
    "dd": ele => applyStyles("dd", ele, "#d2ff00"),
    "div": ele => applyStyles("div", ele, "#f5ff00"),
    "dl": ele => applyStyles("dl", ele, "#ffff00"),
    "dt": ele => applyStyles("dt", ele, "#ffff3f"),
    "figcaption": ele => applyStyles("figcaption", ele, "#ffff7f"),
    "figure": ele => applyStyles("figure", ele, "#ffffbf"),
    "hr": ele => applyStyles("hr", ele, "#ffffff"),
    "li": ele => applyStyles("li", ele, "#ebffeb"),
    "menu": ele => applyStyles("menu", ele, "#c4ffc4"),
    "ol": ele => applyStyles("ol", ele, "#9dff9d"),
    "p": ele => applyStyles("p", ele, "#76ff76"),
    "pre": ele => applyStyles("pre", ele, "#4fff4f"),
    "ul": ele => applyStyles("ul", ele, "#29ff29"),
    /* Inline Text Semantics */
    "a": ele => applyStyles("a", ele, "#00ff00"),
    "abbr": ele => applyStyles("abbr", ele, "#23ff00"),
    "b": ele => applyStyles("b", ele, "#46ff00"),
    "bdi": ele => applyStyles("bdi", ele, "#69ff00"),
    "bdo": ele => applyStyles("bdo", ele, "#8cff00"),
    "br": ele => applyStyles("br", ele, "#afff00"),
    "cite": ele => applyStyles("cite", ele, "#d2ff00"),
    "code": ele => applyStyles("code", ele, "#f5ff00"),
    "data": ele => applyStyles("data", ele, "#ffff00"),
    "dfn": ele => applyStyles("dfn", ele, "#ffff3f"),
    "em": ele => applyStyles("em", ele, "#ffff7f"),
    "i": ele => applyStyles("i", ele, "#ffffbf"),
    "kbd": ele => applyStyles("kbd", ele, "#ffffff"),
    "mark": ele => applyStyles("mark", ele, "#ebffeb"),
    "q": ele => applyStyles("q", ele, "#c4ffc4"),
    "rp": ele => applyStyles("rp", ele, "#9dff9d"),
    "rt": ele => applyStyles("rt", ele, "#76ff76"),
    "ruby": ele => applyStyles("ruby", ele, "#4fff4f"),
    "s": ele => applyStyles("s", ele, "#29ff29"),
    "samp": ele => applyStyles("samp", ele, "#00ff00"),
    "small": ele => applyStyles("small", ele, "#23ff00"),
    "span": ele => applyStyles("span", ele, "#46ff00"),
    "strong": ele => applyStyles("strong", ele, "#69ff00"),
    "sub": ele => applyStyles("sub", ele, "#8cff00"),
    "sup": ele => applyStyles("sup", ele, "#afff00"),
    "time": ele => applyStyles("time", ele, "#d2ff00"),
    "u": ele => applyStyles("u", ele, "#f5ff00"),
    "var": ele => applyStyles("var", ele, "#ffff00"),
    "wbr": ele => applyStyles("wbr", ele, "#ffff3f"),
    /* Image and multimedia */
    "area": ele => applyStyles("area", ele, "#ffff7f"),
    "audio": ele => applyStyles("audio", ele, "#ffffff"),
    "img": ele => applyStyles("img", ele, "#ebffeb"),
    "map": ele => applyStyles("map", ele, "#c4ffc4"),
    "track": ele => applyStyles("track", ele, "#9dff9d"),
    "video": ele => applyStyles("video", ele, "#76ff76"),
    /* Embedded Content */
    "embed": ele => applyStyles("embed", ele, "#4fff4f"),
    "iframe": ele => applyStyles("iframe", ele, "#29ff29"),
    "object": ele => applyStyles("object", ele, "#00ff00"),
    "picture": ele => applyStyles("picture", ele, "#23ff00"),
    "portal": ele => applyStyles("portal", ele, "#46ff00"),
    "source": ele => applyStyles("source", ele, "#69ff00"),
    /* SVG and MathML */
    "svg": ele => applyStyles("svg", ele, "#8cff00"),
    "math": ele => applyStyles("math", ele, "#afff00"),
    /* Scripting */
    "canvas": ele => applyStyles("canvas", ele, "#d2ff00"),
    "noscript": ele => applyStyles("noscript", ele, "#f5ff00"),
    /* Demarcating edits */
    "del": ele => applyStyles("del", ele, "#ffff00"),
    "ins": ele => applyStyles("ins", ele, "#ffff3f"),
    /* Table Content */
    "caption": ele => applyStyles("caption", ele, "#ffff7f"),
    "col": ele => applyStyles("col", ele, "#ffffff"),
    "colgroup": ele => applyStyles("colgroup", ele, "#ebffeb"),
    "table": ele => applyStyles("table", ele, "#c4ffc4"),
    "tbody": ele => applyStyles("tbody", ele, "#9dff9d"),
    "td": ele => applyStyles("td", ele, "#76ff76"),
    "tfoot": ele => applyStyles("tfoot", ele, "#4fff4f"),
    "th": ele => applyStyles("th", ele, "#29ff29"),
    "thead": ele => applyStyles("thead", ele, "#00ff00"),
    "tr": ele => applyStyles("tr", ele, "#23ff00"),
    /* Forms */
    "button": ele => applyStyles("button", ele, "#46ff00"),
    "datalist": ele => applyStyles("datalist", ele, "#69ff00"),
    "fieldset": ele => applyStyles("fieldset", ele, "#8cff00"),
    "form": ele => applyStyles("form", ele, "#afff00"),
    "input": ele => applyStyles("input", ele, "#d2ff00"),
    "label": ele => applyStyles("label", ele, "#f5ff00"),
    "legend": ele => applyStyles("legend", ele, "#ffff00"),
    "meter": ele => applyStyles("meter", ele, "#ffff3f"),
    "optgroup": ele => applyStyles("optgroup", ele, "#ffff7f"),
    "option": ele => applyStyles("option", ele, "#ffffff"),
    "output": ele => applyStyles("output", ele, "#ebffeb"),
    "progress": ele => applyStyles("progress", ele, "#c4ffc4"),
    "select": ele => applyStyles("select", ele, "#9dff9d"),
    "textarea": ele => applyStyles("textarea", ele, "#76ff76"),
    /* Interactive Elements */
    "details": ele => applyStyles("details", ele, "#4fff4f"),
    "dialog": ele => applyStyles("dialog", ele, "#29ff29"),
    "summary": ele => applyStyles("summary", ele, "#00ff00"),
    /* Web Components */
    "slot": ele => applyStyles("slot", ele, "#23ff00"),
    "template": ele => applyStyles("template", ele, "#46ff00"),
}

runtime.onMessage.addListener(message => options = message || {})